// TEMPORARY DATA

export let role = "admin";

export const teachersData = [
  {
    id: 1,
    teacherId: "1234567890",
    name: "Thabo Mokoena",
    email: "thabo@mokoena.com",
    photo: "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Math", "Geometry"],
    classes: ["1B", "2A", "3C"],
    address: "Maseru",
  },
  {
    id: 2,
    teacherId: "1234567890",
    name: "Matseliso Ntai",
    email: "matseliso@ntai.com",
    photo: "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Physics", "Chemistry"],
    classes: ["5A", "4B", "3C"],
    address: "Maseru",
  },
  {
    id: 3,
    teacherId: "1234567890",
    name: "Tumelo Molapo",
    email: "tumelo@molapo.com",
    photo: "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "Maseru",
  },
  {
    id: 4,
    teacherId: "1234567890",
    name: "Khotso Nkhasi",
    email: "khotso@nkhasi.com",
    photo: "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["History"],
    classes: ["5A", "4B", "3C"],
    address: "Maseru",
  },
  {
    id: 5,
    teacherId: "1234567890",
    name: "Malebohang Mokhothu",
    email: "malebohang@mokhothu.com",
    photo: "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Music", "History"],
    classes: ["5A", "4B", "3C"],
    address: "Maseru",
  },
  {
    id: 6,
    teacherId: "1234567890",
    name: "Masego Phiri",
    email: "masego@phiri.com",
    photo: "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Physics"],
    classes: ["5A", "4B", "3C"],
    address: "Maseru",
  },
  {
    id: 7,
    teacherId: "1234567890",
    name: "Sello Majara",
    email: "sello@majara.com",
    photo: "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["English", "Spanish"],
    classes: ["5A", "4B", "3C"],
    address: "Maseru",
  },
  {
    id: 8,
    teacherId: "1234567890",
    name: "Lerato Letsie",
    email: "lerato@letsie.com",
    photo: "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Math", "Geometry"],
    classes: ["5A", "4B", "3C"],
    address: "Maseru",
  },
  {
    id: 9,
    teacherId: "1234567890",
    name: "Paballo Mofokeng",
    email: "paballo@mofokeng.com",
    photo: "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Literature", "English"],
    classes: ["5A", "4B", "3C"],
    address: "Maseru",
  },
  {
    id: 10,
    teacherId: "1234567890",
    name: "Refiloe Khoabane",
    email: "refiloe@khoabane.com",
    photo: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "Maseru",
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "1234567890",
    name: "Thabo Mokoena",
    email: "thabo@mokoena.com",
    photo: "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "1B",
    address: "Maseru",
  },
  {
    id: 2,
    studentId: "1234567890",
    name: "Matseliso Ntai",
    email: "matseliso@ntai.com",
    photo: "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Maseru",
  },
  {
    id: 3,
    studentId: "1234567890",
    name: "Tumelo Molapo",
    email: "tumelo@molapo.com",
    photo: "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Maseru",
  },
  {
    id: 4,
    studentId: "1234567890",
    name: "Khotso Nkhasi",
    email: "khotso@nkhasi.com",
    photo: "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Maseru",
  },
  {
    id: 5,
    studentId: "1234567890",
    name: "Malebohang Mokhothu",
    email: "malebohang@mokhothu.com",
    photo: "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Maseru",
  },
  {
    id: 6,
    studentId: "1234567890",
    name: "Masego Phiri",
    email: "masego@phiri.com",
    photo: "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Maseru",
  },
  {
    id: 7,
    studentId: "1234567890",
    name: "Sello Majara",
    email: "sello@majara.com",
    photo: "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Maseru",
  },
  {
    id: 8,
    studentId: "1234567890",
    name: "Lerato Letsie",
    email: "lerato@letsie.com",
    photo: "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Maseru",
  },
  {
    id: 9,
    studentId: "1234567890",
    name: "Paballo Mofokeng",
    email: "paballo@mofokeng.com",
    photo: "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Maseru",
  },
  {
    id: 10,
    studentId: "1234567890",
    name: "Refiloe Khoabane",
    email: "refiloe@khoabane.com",
    photo: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Maseru",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "Ntate Mokoena",
    students: ["Thabo Mokoena"],
    email: "ntate@mokoena.com",
    phone: "1234567890",
    address: "Maseru",
  },
  {
    id: 2,
    name: "'Me Ntai",
    students: ["Matseliso Ntai"],
    email: "me@ntai.com",
    phone: "1234567890",
    address: "Maseru",
  },
  {
    id: 3,
    name: "Ntate Molapo",
    students: ["Tumelo Molapo"],
    email: "ntate@molapo.com",
    phone: "1234567890",
    address: "Maseru",
  },
  {
    id: 4,
    name: "Ntate Nkhasi",
    students: ["Khotso Nkhasi", "Kamohelo Nkhasi"],
    email: "ntate@nkhasi.com",
    phone: "1234567890",
    address: "Maseru",
  },
  {
    id: 5,
    name: "'Me Mokhothu",
    students: ["Malebohang Mokhothu"],
    email: "me@mokhothu.com",
    phone: "1234567890",
    address: "Maseru",
  },
  {
    id: 6,
    name: "'Me Phiri",
    students: ["Masego Phiri"],
    email: "me@phiri.com",
    phone: "1234567890",
    address: "Maseru",
  },
  {
    id: 7,
    name: "Ntate Majara",
    students: ["Sello Majara", "Kelello Majara"],
    email: "ntate@majara.com",
    phone: "1234567890",
    address: "Maseru",
  },
  {
    id: 8,
    name: "'Me Letsie",
    students: ["Lerato Letsie"],
    email: "me@letsie.com",
    phone: "1234567890",
    address: "Maseru",
  },
  {
    id: 9,
    name: "Ntate Mofokeng",
    students: ["Paballo Mofokeng", "Lits'episo Mofokeng"],
    email: "ntate@mofokeng.com",
    phone: "1234567890",
    address: "Maseru",
  },
  {
    id: 10,
    name: "'Me Khoabane",
    students: ["Refiloe Khoabane"],
    email: "me@khoabane.com",
    phone: "1234567890",
    address: "Maseru",
  },
];

export const subjectsData = [
  {
    id: 1,
    name: "Lipalo",
    teachers: ["Thabo Mokoena", "Lerato Letsie"],
  },
  {
    id: 2,
    name: "Sesotho",
    teachers: ["Sello Majara", "Paballo Mofokeng"],
  },
  {
    id: 3,
    name: "Fisiks",
    teachers: ["Matseliso Ntai", "Masego Phiri"],
  },
  {
    id: 4,
    name: "Khemistri",
    teachers: ["Matseliso Ntai", "Refiloe Khoabane"],
  },
  {
    id: 5,
    name: "Biology",
    teachers: ["Tumelo Molapo", "Refiloe Khoabane"],
  },
  {
    id: 6,
    name: "Nalane",
    teachers: ["Khotso Nkhasi", "Malebohang Mokhothu"],
  },
  {
    id: 7,
    name: "Jografi",
    teachers: ["Khotso Nkhasi", "Sello Majara"],
  },
  {
    id: 8,
    name: "Boitšoaro",
    teachers: ["Malebohang Mokhothu", "Lerato Letsie"],
  },
  {
    id: 9,
    name: "Mmino",
    teachers: ["Malebohang Mokhothu", "Paballo Mofokeng"],
  },
  {
    id: 10,
    name: "Litšomo",
    teachers: ["Paballo Mofokeng", "Sello Majara"],
  },
];

export const classesData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    grade: 1,
    supervisor: "Thabo Mokoena",
  },
  {
    id: 2,
    name: "2B",
    capacity: 22,
    grade: 2,
    supervisor: "Matseliso Ntai",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    grade: 3,
    supervisor: "Tumelo Molapo",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    grade: 4,
    supervisor: "Khotso Nkhasi",
  },
  {
    id: 5,
    name: "5A",
    capacity: 16,
    grade: 5,
    supervisor: "Malebohang Mokhothu",
  },
  {
    id: 6,
    name: "5B",
    capacity: 20,
    grade: 5,
    supervisor: "Masego Phiri",
  },
  {
    id: 7,
    name: "7A",
    capacity: 18,
    grade: 7,
    supervisor: "Sello Majara",
  },
  {
    id: 8,
    name: "6B",
    capacity: 22,
    grade: 6,
    supervisor: "Lerato Letsie",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    grade: 6,
    supervisor: "Paballo Mofokeng",
  },
  {
    id: 10,
    name: "6D",
    capacity: 20,
    grade: 6,
    supervisor: "Refiloe Khoabane",
  },
];

export const lessonsData = [
  {
    id: 1,
    subject: "Mathematics",
    class: "1A",
    teacher: "Thabo Mokoena",
  },
  {
    id: 2,
    subject: "Sesotho",
    class: "2A",
    teacher: "Sello Majara",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Tumelo Molapo",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Khotso Nkhasi",
  },
  {
    id: 5,
    subject: "Boitšoaro",
    class: "4A",
    teacher: "Malebohang Mokhothu",
  },
  {
    id: 6,
    subject: "Mmino",
    class: "5A",
    teacher: "Malebohang Mokhothu",
  },
  {
    id: 7,
    subject: "Nalane",
    class: "6A",
    teacher: "Khotso Nkhasi",
  },
  {
    id: 8,
    subject: "Jografi",
    class: "6B",
    teacher: "Sello Majara",
  },
  {
    id: 9,
    subject: "Fisiks",
    class: "6C",
    teacher: "Masego Phiri",
  },
  {
    id: 10,
    subject: "Khemistri",
    class: "4B",
    teacher: "Matseliso Ntai",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "Mathematics",
    class: "1A",
    teacher: "Thabo Mokoena",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "Sesotho",
    class: "2A",
    teacher: "Sello Majara",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Tumelo Molapo",
    date: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Khotso Nkhasi",
    date: "2025-01-01",
  },
  {
    id: 5,
    subject: "Boitšoaro",
    class: "4A",
    teacher: "Malebohang Mokhothu",
    date: "2025-01-01",
  },
  {
    id: 6,
    subject: "Mmino",
    class: "5A",
    teacher: "Malebohang Mokhothu",
    date: "2025-01-01",
  },
  {
    id: 7,
    subject: "Nalane",
    class: "6A",
    teacher: "Khotso Nkhasi",
    date: "2025-01-01",
  },
  {
    id: 8,
    subject: "Jografi",
    class: "6B",
    teacher: "Sello Majara",
    date: "2025-01-01",
  },
  {
    id: 9,
    subject: "Fisiks",
    class: "7A",
    teacher: "Masego Phiri",
    date: "2025-01-01",
  },
  {
    id: 10,
    subject: "Khemistri",
    class: "8A",
    teacher: "Matseliso Ntai",
    date: "2025-01-01",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Mathematics",
    class: "1A",
    teacher: "Thabo Mokoena",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "Sesotho",
    class: "2A",
    teacher: "Sello Majara",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Tumelo Molapo",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Khotso Nkhasi",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    subject: "Boitšoaro",
    class: "4A",
    teacher: "Malebohang Mokhothu",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    subject: "Mmino",
    class: "5A",
    teacher: "Malebohang Mokhothu",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Khotso Nkhasi",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    subject: "Jografi",
    class: "6B",
    teacher: "Sello Majara",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    subject: "Fisiks",
    class: "7A",
    teacher: "Masego Phiri",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    subject: "Khemistri",
    class: "8A",
    teacher: "Matseliso Ntai",
    dueDate: "2025-01-01",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Mathematics",
    class: "1A",
    teacher: "Thabo Mokoena",
    student: "Thabo Mokoena",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    subject: "Sesotho",
    class: "2A",
    teacher: "Sello Majara",
    student: "Matseliso Ntai",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Tumelo Molapo",
    student: "Tumelo Molapo",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Khotso Nkhasi",
    student: "Khotso Nkhasi",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 5,
    subject: "Boitšoaro",
    class: "4A",
    teacher: "Malebohang Mokhothu",
    student: "Malebohang Mokhothu",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 6,
    subject: "Mmino",
    class: "5A",
    teacher: "Malebohang Mokhothu",
    student: "Masego Phiri",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Khotso Nkhasi",
    student: "Sello Majara",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 8,
    subject: "Jografi",
    class: "6B",
    teacher: "Sello Majara",
    student: "Lerato Letsie",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 9,
    subject: "Fisiks",
    class: "7A",
    teacher: "Masego Phiri",
    student: "Paballo Mofokeng",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 10,
    subject: "Khemistri",
    class: "8A",
    teacher: "Matseliso Ntai",
    student: "Refiloe Khoabane",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Leeto la Letšeng",
    class: "1A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Pikinike",
    class: "2A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Leeto la Lebopo",
    class: "3A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Leeto la Musiamo",
    class: "4A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Khonasete ea Mmino",
    class: "5A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Ponahalo ea Lialoli",
    class: "1B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "Leeto la Letšeng",
    class: "2B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Pallo ea Baesekele",
    class: "3B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Ponahalo ea Boitšoaro",
    class: "4B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Mekhahlelo ea Lipapali",
    class: "5B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "Mabapi le Tekolo ea Mathematics 4A",
    class: "4A",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "Mabapi le Tekolo ea Mathematics 3A",
    class: "3A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "Mabapi le Tekolo ea Mathematics 3B",
    class: "3B",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "Mabapi le Tekolo ea Mathematics 6A",
    class: "6A",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "Mabapi le Tekolo ea Mathematics 8C",
    class: "8C",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "Mabapi le Tekolo ea Mathematics 2A",
    class: "2A",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "Mabapi le Tekolo ea Mathematics 4C",
    class: "4C",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "Mabapi le Tekolo ea Mathematics 4B",
    class: "4B",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "Mabapi le Tekolo ea Mathematics 3C",
    class: "3C",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "Mabapi le Tekolo ea Mathematics 1C",
    class: "1C",
    date: "2025-01-01",
  },
];

// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
export const calendarEvents = [
  {
    title: "Lipalo",
    allDay: false,
    start: new Date(2026, 1, 15, 8, 0),
    end: new Date(2026, 1, 15, 8, 45),
  },
  {
    title: "Sesotho",
    allDay: false,
    start: new Date(2024, 7, 12, 9, 0),
    end: new Date(2024, 7, 12, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 12, 10, 0),
    end: new Date(2024, 7, 12, 10, 45),
  },
  {
    title: "Fisiks",
    allDay: false,
    start: new Date(2024, 7, 12, 11, 0),
    end: new Date(2024, 7, 12, 11, 45),
  },
  {
    title: "Khemistri",
    allDay: false,
    start: new Date(2024, 7, 12, 13, 0),
    end: new Date(2024, 7, 12, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 12, 14, 0),
    end: new Date(2024, 7, 12, 14, 45),
  },
  {
    title: "Sesotho",
    allDay: false,
    start: new Date(2024, 7, 13, 9, 0),
    end: new Date(2024, 7, 13, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 13, 10, 0),
    end: new Date(2024, 7, 13, 10, 45),
  },
  {
    title: "Fisiks",
    allDay: false,
    start: new Date(2024, 7, 13, 11, 0),
    end: new Date(2024, 7, 13, 11, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 13, 14, 0),
    end: new Date(2024, 7, 13, 14, 45),
  },
  {
    title: "Lipalo",
    allDay: false,
    start: new Date(2024, 7, 14, 8, 0),
    end: new Date(2024, 7, 14, 8, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 14, 10, 0),
    end: new Date(2024, 7, 14, 10, 45),
  },
  {
    title: "Khemistri",
    allDay: false,
    start: new Date(2024, 7, 14, 13, 0),
    end: new Date(2024, 7, 14, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 14, 14, 0),
    end: new Date(2024, 7, 14, 14, 45),
  },
  {
    title: "Sesotho",
    allDay: false,
    start: new Date(2024, 7, 15, 9, 0),
    end: new Date(2024, 7, 15, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 15, 10, 0),
    end: new Date(2024, 7, 15, 10, 45),
  },
  {
    title: "Fisiks",
    allDay: false,
    start: new Date(2024, 7, 15, 11, 0),
    end: new Date(2024, 7, 15, 11, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 15, 14, 0),
    end: new Date(2024, 7, 15, 14, 45),
  },
  {
    title: "Lipalo",
    allDay: false,
    start: new Date(2024, 7, 16, 8, 0),
    end: new Date(2024, 7, 16, 8, 45),
  },
  {
    title: "Sesotho",
    allDay: false,
    start: new Date(2024, 7, 16, 9, 0),
    end: new Date(2024, 7, 16, 9, 45),
  },
  {
    title: "Fisiks",
    allDay: false,
    start: new Date(2024, 7, 16, 11, 0),
    end: new Date(2024, 7, 16, 11, 45),
  },
  {
    title: "Khemistri",
    allDay: false,
    start: new Date(2024, 7, 16, 13, 0),
    end: new Date(2024, 7, 16, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 16, 14, 0),
    end: new Date(2024, 7, 16, 14, 45),
  },
];